name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: ${{ matrix.distribution.image }}-${{ matrix.distribution.version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - image: clever-tools
            version: "latest"
          - image: clever-tools
            version: "2.8.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          docker build \
            --no-cache \
            --rm \
            --file=Dockerfile \
            --tag=diodonfrost/${{ matrix.distribution.image }}:${{ matrix.distribution.version }} \
            --build-arg VERSION=${{ matrix.distribution.version }} \
            .
