name: Push

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: ${{ matrix.distribution.image }}-${{ matrix.distribution.version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - image: clever-tools
            version: "latest"
          - image: clever-tools
            version: "2.8.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          docker build \
            --no-cache \
            --rm \
            --file=Dockerfile \
            --tag=diodonfrost/${{ matrix.distribution.image }}:${{ matrix.distribution.version }} \
            --build-arg VERSION=${{ matrix.distribution.version }} \
            .

      - name: Push Docker image to Docker Hub
        run: |
          # Login on dockerhub.io before pushing
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Pushing image to dockerhub
          docker push diodonfrost/${{ matrix.distribution.image }}:${{ matrix.distribution.version }}

      - name: Push Docker image to Github Docker registry
        run: |
          # Login on Github Docker registry before pushing
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u diodonfrost --password-stdin

          # Pushing image to Github Docker registry
          docker tag diodonfrost/${{ matrix.distribution.image }}:${{ matrix.distribution.version }} ghcr.io/diodonfrost/${{ matrix.distribution.image }}:${{ matrix.distribution.version }}
          docker push ghcr.io/diodonfrost/${{ matrix.distribution.image }}:${{ matrix.distribution.version }}
